### ISSUE TITLE
Do not require Brunch

### ISSUE THREAD

**Issue by avdgaag** [gjaldon/phoenix-static-buildpack#7]
Currently, the readme states that you can use other build tools than Brunch in your postcompile script — but this buildpack is only activated if you do actually have a `brunch-config.js` file present. This is not necessarily the case, if you switched to Gulp or Webpack or something.

**Comment by gjaldon** [comment]
@avdgaag thanks for this! Sorry took me a while to get to this. Just realized I wasn't watching this repo. 

Anyway, fix has just been pushed. :+1:
