### ISSUE TITLE
Rename postcompile => compile

### ISSUE THREAD

**Issue by ericmj** [gjaldon/phoenix-static-buildpack#8]
It's actually not doing post-compilation, it's performing the actual job of the buildpack. I would also suggest moving the filename to a configuration so that it doesn't conflict with other buildtools: https://github.com/HashNuke/heroku-buildpack-elixir/pull/39/files#diff-04c6e90faac2675aa89e2176d2eec7d8R59.

**Comment by gjaldon** [comment]
You're right it makes more sense to use `compile`. Will also provide a config option to customize the filename. Will work on this later tonight. Thanks for the feedback!

**Comment by gjaldon** [comment]
https://github.com/gjaldon/phoenix-static-buildpack/commit/5228f7ab6720c5a60beda15aeb82a7b7416b42d7 addresses this :smile:
